name: Increment Tag and Run Rundek

on:
  pull_request:
    types:
      - closed

jobs:
  increment-tag-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get branch name
      id: get_branch
      run: |
        branch_name=$(echo $GITHUB_REF | cut -d "/" -f 3)
        echo "::set-output name=branch::$branch_name"
    
    - name: Get last tag
      id: get_tag
      run: |
        last_tag=$(git describe --tags --abbrev=0)
        echo "::set-output name=tag::$last_tag"
    
    - name: Extract version parts
      id: extract_version
      run: |
        tag=${{ steps.get_tag.outputs.tag }}
        version=$(echo $tag | cut -d "v" -f 2)
        echo "::set-output name=version::$version"
    
    - name: Increment version
      id: increment_version
      run: |
        version=${{ steps.extract_version.outputs.version }}
        new_version=$((version + 1))
        echo "::set-output name=new_version::$new_version"
    
    - name: Create new tag
      run: |
        branch_name=${{ steps.get_branch.outputs.branch }}
        new_version=${{ steps.increment_version.outputs.new_version }}
        new_tag="v$new_version-$branch_name"
        git tag $new_tag
    
    - name: Push new tag
      run: |
        new_version=${{ steps.increment_version.outputs.new_version }}
        new_tag="v$new_version-$branch_name"
        git push origin $new_tag
    